import '@fortawesome/fontawesome-svg-core/styles.css'
import './globals.css'

import GlobalStyles from '@/styles/global'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Provider from './provider'
import { config } from '@fortawesome/fontawesome-svg-core'

config.autoAddCss = false

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {GlobalStyles}
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
