import { notoSansKr } from '@/styles'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(notoSansKr.className)
  return (
    <html lang='en'>
      <body className={notoSansKr.className}>{children}</body>
    </html>
  )
}
